// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlPXPBgPAylZ-c2JAO5RvrdDzmyMjLIAI',
    appId: '1:1074558157752:web:c81c27e49b35297d2f854d',
    messagingSenderId: '1074558157752',
    projectId: 'kimpul-1832',
    authDomain: 'kimpul-1832.firebaseapp.com',
    storageBucket: 'kimpul-1832.firebasestorage.app',
    measurementId: 'G-8FXZ2998D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7BmkSaEJk8o1z43U4bcoQLBxawcihZQs',
    appId: '1:1074558157752:android:20846af0126f34672f854d',
    messagingSenderId: '1074558157752',
    projectId: 'kimpul-1832',
    storageBucket: 'kimpul-1832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1l15q2XtZ95AGWb3isHjGj2ljjEICIzk',
    appId: '1:1074558157752:ios:301960b4a18ed3092f854d',
    messagingSenderId: '1074558157752',
    projectId: 'kimpul-1832',
    storageBucket: 'kimpul-1832.firebasestorage.app',
    iosBundleId: 'com.example.kimpul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1l15q2XtZ95AGWb3isHjGj2ljjEICIzk',
    appId: '1:1074558157752:ios:301960b4a18ed3092f854d',
    messagingSenderId: '1074558157752',
    projectId: 'kimpul-1832',
    storageBucket: 'kimpul-1832.firebasestorage.app',
    iosBundleId: 'com.example.kimpul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlPXPBgPAylZ-c2JAO5RvrdDzmyMjLIAI',
    appId: '1:1074558157752:web:68b7a42ff819de3e2f854d',
    messagingSenderId: '1074558157752',
    projectId: 'kimpul-1832',
    authDomain: 'kimpul-1832.firebaseapp.com',
    storageBucket: 'kimpul-1832.firebasestorage.app',
    measurementId: 'G-BQLTVFZGZ6',
  );
}
